/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package antreanode

import (
        "github.com/vmware/go-vmware-nsxt/manager"
)


type PolicyAntreaNodeRegistrationMessage struct {
	// The Antrea Node infomation for registration.
	AntreaNode *PolicyAntreaNode `json:"antrea_node"`
	// We should afford the certificate in this message client to let Antrea Node finish the registration.
	MsgClientInfo *manager.MsgClientInfo `json:"msg_client_info"`
}
